stages:
  - install
  - test

install:
  stage: install
  image: node:20
  script:
    - cd sosial_media
    - npm install

test:
  stage: test
  image: node:20
  script:
    - cd sosial_media
    - npm test
    