stages:
  - install
  - test

install:
  stage: install
  image: node:20
  script:
    - echo "Current directory:"
    - pwd
    - ls -al
    - cd sosial_media
    - ls -al
    - npm install

test:
  stage: test
  image: node:20
  script:
    - cd sosial_media
    - npm test
    