stages:
  - install
  - test

install:
  stage: install
  image: node:20
  script:
    - cd social_mediaplatform
    - npm install

test:
  stage: test
  image: node:20
  script:
    - cd social_mediaplatform
    - npm test