stages:
  - install
  - test

install:
  stage: install
  image: node:20
  script:
    - echo "Installing dependencies..."
    - pwd
    - ls -al
    - cd sosial_media
    - ls -al
    - cat package.json
    - npm install

test:
  stage: test
  image: node:20
  script:
    - echo "Current directory:"
    - pwd
    - cd sosial_media
    - echo "List files:"
    - ls -al
    - npm run testapi
