stages:
  - install
  - test

variables:
  POSTGRES_DB: social_test
  POSTGRES_USER: happy29
  POSTGRES_PASSWORD: "19960110"
  DB_HOST: postgres-db
  DB_PORT: 5432
  NODE_ENV: test
  TEST_MODE: "true"

services:
  - name: postgres:16.4
    alias: postgres-db

install:
  stage: install
  image: node:20
  script:
    - echo "Before cd:"
    - pwd
    - ls -al
    - cd $CI_PROJECT_DIR
    - echo "After cd:"
    - pwd
    - ls -al
    - git status
    - cat package.json
    - npm install

test:
  stage: test
  image: node:20
  script:
    - cd $CI_PROJECT_DIR
    - echo "Waiting for PostgreSQL..."
    - sleep 5
    - npm run testapi
